# Netlify configuration file - Simplified for UI Preview
# Updated on March 7, 2025 with simplified build approach

[build]
  # Use repository root
  base = "/"
  
  # Output directory for static files
  publish = "public"
  
  # Simple build command using Node.js script
  command = "node netlify.js"

# Redirect all API requests to a placeholder
[[redirects]]
  from = "/api/*"
  to = "/api-placeholder.json"
  status = 200

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Set environment variables
[build.environment]
  NODE_VERSION = "18"

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
