# Netlify configuration for UI Showcase

[build]
  base = "ui-showcase"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/ui-showcase/*"
  to = "/ui-showcase/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
